language: r
sudo: false
cache: packages
env:
  global:
  - secure: FtdVdYuEv0M55b16iyVCzl5BkEeN3RIXxACvOcQsG8Lnlnv6VDpPv/F6nYdK/wyreDiprT1q38sShp24IottXQ5brFtTWBrAhO7e2qjEYyrsypa6dTUye6LFRNQeOtYcqL4ekDH3SBCboP/EAddazIzeXG/mT5YOZHwRzddjPvJOj9TXQ0cesc701a5Zu2DEEKv0iAzIK7H9m0tg6/fBPKdLM4Q5Ou10bfjZ0lZZRQAQ53uNYnCs+304Yh9g+u472zxCgjy6yRJPMMK72A8fYxuM4MXJAFj7vblSwtCXpu9WBaRCsFfnMdWjFMFhfSpzqo1aNf1gE7jg0RNrsp/DJF75T9PqUkqaCcl/qPKF0j2+/RrvWU4paoi8dkCmQ0Nr1rd//VofA4uLnxqZnRYZuDH61Qa2xwTbLqV8Svg5TMbEkX8ovZU9iPslpjYxHuM9cA6SyCx9ax5F/8NxVYir4j+zNBQ3n+BYoThonLMvglBBtPrkKCogibzgFj+Wk5ctKAnNz09HlrR7Sq2zZ14cvm391zyt5+c/A0VcO0om2XWJqmEwvHOQTFfrkDCF64UL56/cCH4OD4t3Fux08dUUeXX+eu7UUkn9LhawwSGO10T6W05F1vf6L0csbUX5OH4wP5vX4xGkxgVpEEPsj2NuB3G5BEvH7W+c6CAQsxt4w3Q=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
